<a href="https://colab.research.google.com/github/ardeeshany/Deep-Learning-Projects/blob/main/2022_04_DL_Pytorch_Image.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notes

- Similar to numpy, mainly based on matrix multiplications -> Tensors

- An **object** is being created from a **class**

- Using classes help you: 1. A **user-defined** structure 2. Leveraging **inheritance**

- **Tensor:** A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators. The number of dimensions a tensor has is called its rank and the length in each dimension describes its shape. A tensor with one dimension can be thought of as a vector, a tensor with two dimensions as a matrix and a tensor with three dimensions can be thought of as a cuboid.

- One important thing about loss functions is that they should be differentiable! For classification, accuracy is not differentiable → we use **cross-entropy** which is both differentiable and provides and estimate of the accuracy of the selected class!

In [ ]:
import torch
print("### Rank 2: Matrix")
print(torch.tensor([[1,2], 
                    [3,5]]).shape)

print("#### Rank 3: Cuboid")
print(torch.tensor([   
                    [[1,2, 5], 
                     [3,5, 5]],
                       
                    [[4,5, 6], 
                     [4,5, 6]]    
                    ]))
print(torch.tensor([    [[1,2, 5], [3,5, 5]],   [[4,5, 6], [4,5, 6]]    ]).shape)

print("####")
print(torch.tensor([[1,2], [3,5]]))
print("#####")
print(torch.tensor([[1,2], [3,5]])[0])
print("#####")
torch.tensor([[1,2], [3,5]])[0][0]

### Rank 2: Matrix
torch.Size([2, 2])
#### Rank 3: Cuboid
tensor([[[1, 2, 5],
         [3, 5, 5]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])
####
tensor([[1, 2],
        [3, 5]])
#####
tensor([1, 2])
#####


tensor(1)

In [ ]:
print(torch.rand(2,2))
a = torch.rand(2,2)
b = torch.rand(2,2)
torch.matmul(a,b)  # dot product

tensor([[0.5171, 0.8522],
        [0.6582, 0.4905]])


tensor([[0.1112, 0.1092],
        [0.1071, 0.1079]])

In [ ]:
# Specials
print(torch.zeros(2,3)) 
print("#")
print(torch.ones(2,2))
print("#")
print(torch.eye(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
#
tensor([[1., 1.],
        [1., 1.]])
#
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
import numpy as np
torch.from_numpy(np.zeros((2,2))) # torch.numpy()

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [ ]:
# Class
class Student:
    def __init__(self, first, last, age):  # have to have 'self', but may contain other attributes
      self.first = first
      self.last = last
      self.age = age
    
    def Info(self):  # method
      print("The first name is " + self.first + " and the last name is " + self.last + ". It is " + str(self.age) + " years old")

    def birthday(self):
        self.age += 1

In [ ]:
M1 = Student("John", "Doe", 30)
M1.Info()

The first name is John and the last name is Doe. It is 30 years old


In [ ]:
# Creating a class of NN
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):  # inherit from nn.Module
  def __init__(self):
      super(Net, self).__init__()
      self.fc1 = nn.Linear(10, 20)  # Dense layer
      self.fc2 = nn.Linear(20, 20)  # Dense layer
      self.output = nn.Linear(20, 4)


  def forward(self, x): # forward method
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))
      x = self.output(x)
      return x

In [ ]:
MyNet = Net()
input = torch.rand(10)
MyNet.forward(input)   # return feedforward with the random weighted

tensor([ 0.2097,  0.1332, -0.1511, -0.1417], grad_fn=<AddBackward0>)

In [ ]:
import torch.nn as nn
relu = nn.ReLU()
inp = torch.tensor([2., -1.])
relu(inp)

tensor([2., 0.])

In [ ]:
out = torch.tensor([[.2, .1, 4.5]])
gr = torch.tensor([2]) # the last number out of [.2, .1, -1.5] is the right one -> p = [0, 0, 1]
criterion = nn.CrossEntropyLoss() # based on Kullback-Leibler Divergence (diffenrentiable measure explain how two dist are close to each other!)
print(criterion(out, gr)) # = Sum(-tlog(p)) -> < 0.02 great probabilities, <0.05 acceptable!
(0 + 0 + -1*np.log(np.exp(4.5)/(np.exp(0.2) + np.exp(0.1) + np.exp(4.5))))

tensor(0.0255)


0.02551753947901458

## Load Data

- **Torchvision** is a library for Computer Vision that goes hand in hand with PyTorch. It has utilities for efficient Image and Video **transformations**, some commonly used **pre-trained models**, and some **datasets**
  - A batch of Tensor Images is a tensor of (B, C, H, W) shape, where B is a number of images in the batch, and C is the number of channels.

- The `torch.utils.data.DataLoader` class is designed so that it can be iterated using the **enumerate()** function, which returns a tuple with the current batch zero-based index value, and the actual batch of data. With using this function, we can later leverage nice functionalities such as multiprocessing

In [1]:
import torch
import torch.utils.data

import torchvision
import torchvision.transforms as transforms
transform = transforms.Compose([transforms.ToTensor()])

In [2]:
train_data = torchvision.datasets.CIFAR10(root = "./", train = True, download=True, transform = transform)
test_data = torchvision.datasets.CIFAR10(root = "./", train = False, download=True, transform = transform)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./cifar-10-python.tar.gz to ./
Files already downloaded and verified


In [3]:
train_data.data.shape, test_data.data.shape 

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [ ]:
train_loader = torch.utils.data.DataLoader(train_data, batch_size = 32, shuffle=True, num_workers=4)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = 32, shuffle=True, num_workers=4)

In [5]:
train_loader.dataset.data.shape, test_loader.dataset.data.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [6]:
train_loader.batch_size, test_loader.batch_size

(32, 32)

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(32*32*3, 500)
        self.fc2 = nn.Linear(500, 10)  # 10 = num of outputs

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return self.fc2(x)


## Training the network

In [8]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params = net.parameters(), lr = 0.001)


for epoch in range(1):
    for i, data in enumerate(train_loader):   # train_loader = (50K, 32, 32, 3)& create 4 worker process; data[0] = X = (32, 3, 32, 32) ; data[1] = Y = [32] = one label for each observation
        inputs, labels = data
        inputs = inputs.view(-1, 32*32*3)  # puts all the images into a vector 

        optimizer.zero_grad() # set all the gradients to zero -> not added from the previous iteration!
        
        
        # run the network: Forward + Backward + Optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        
        loss.backward()   
        
        optimizer.step()  # update weights: performs a single optimization step




/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


## Testing the network

In [ ]:
correct, total = 0, 0
predictions = []
net.eval() # go in the test/evaluation mode

for i, data in enumerate(test_loader, 0):
    inputs, labels = data  # labels = [32,1] , inputs = [batch = 32, channel = 3, 32, 32]

    inputs = inputs.view(-1, 32*32*3) # = (32, 3072) (batch_zie = 32)

    outputs = net(inputs) # (32, 10)   
    _, predicted = torch.max(outputs.data, dim = 1) # (32, 1) -> For each vector of outputs (1,10), it takes their max! -> output two items: The first returns real values, and secnod is the indexes -> (32, 1) each of them
    predictions.append(outputs)
    
    total += labels.size(0) # generally returns a tensor -> .size(0) returns numeric value
    
    correct += (predicted == labels).sum().item()  # .sum() returns a tensor, .items() returns numeric value

print("The test accuracy: " + str(100*(correct/total)))

# CNN

- Convolving: Doing dot product between the image and the filter!

- 2 ways of CNN in `pytorch`: Functional (`torch.nn.functional`) vs OOP (`torch.nn`)

```python
nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
nn.MaxPool2d(2) or nn.AvgPool2d(2)
```

### CNN on CIFAR10 using Pytorch

In [27]:
# Prepare Data

import torch
import torch.nn as nn

import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

In [ ]:
train_data = torchvision.datasets.CIFAR10(root = "./", train = True, download = True, transform = transform)
test_data = torchvision.datasets.CIFAR10(root = "./", train = False, download = True, transform = transform)

In [30]:
trainloader = torch.utils.data.DataLoader(train_data, shuffle=True ,batch_size = 128, num_workers=4)
testloader = torch.utils.data.DataLoader(test_data, shuffle = True, batch_size = 128, num_workers = 4)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [37]:
# Building a CNN

class Net(nn.Module):

    def __init__(self, num_class = 1000):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channels = 3, out_channels = 32, kernel_size = 3, padding = 1)
        self.conv2 = nn.Conv2d(in_channels = 32, out_channels = 64, kernel_size = 3, padding = 1)
        self.conv3 = nn.Conv2d(in_channels = 64, out_channels = 128, kernel_size = 3 , padding = 1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc = nn.Linear(128*4*4, num_class)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(-1, 128*4*4)
        return self.fc(x)


In [38]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params = net.parameters(), lr = 0.001)


In [39]:
for epoch in range(1):
    for i, data in enumerate(train_loader):   # train_loader = (50K, 32, 32, 3)& create 4 worker process; data[0] = X = (32, 3, 32, 32) ; data[1] = Y = [32] = one label for each observation
        inputs, labels = data
        
        optimizer.zero_grad() # set all the gradients to zero -> not added from the previous iteration!
        
        
        # run the network: Forward + Backward + Optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        
        loss.backward()   
        
        optimizer.step()  # update weights: performs a single optimization step




/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [40]:
correct, total = 0, 0
predictions = []
net.eval() # go in the test/evaluation mode

for i, data in enumerate(test_loader, 0):
    inputs, labels = data  # labels = [32,1] , inputs = [batch = 32, channel = 3, 32, 32]

    outputs = net(inputs) # (32, 10)   
    _, predicted = torch.max(outputs.data, dim = 1) # (32, 1) -> For each vector of outputs (1,10), it takes their max! -> output two items: The first returns real values, and secnod is the indexes -> (32, 1) each of them
    predictions.append(outputs)
    
    total += labels.size(0) # generally returns a tensor -> .size(0) returns numeric value
    
    correct += (predicted == labels).sum().item()  # .sum() returns a tensor, .items() returns numeric value

print("The test accuracy: " + str(100*(correct/total)))

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


The test accuracy: 57.11000000000001
