<a href="https://colab.research.google.com/github/ardeeshany/Deep-Learning-Projects/blob/main/2022_04_DL_Pytorch_Image.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notes

- Similar to numpy, mainly based on matrix multiplications -> Tensors
- An **object** is created from the **class**
- Using classes help you: 1. A **user-defined** structure 2. Leveraging **inheritance**

In [2]:
import torch

In [34]:
print(torch.tensor([[1,2], [3,5]]).shape)
print("####")
print(torch.tensor([    [[1,2, 5], [3,5, 5]],   [[4,5, 6], [4,5, 6]]    ]))
print(torch.tensor([    [[1,2, 5], [3,5, 5]],   [[4,5, 6], [4,5, 6]]    ]).shape)
print("####")
print(torch.tensor([[1,2], [3,5]]))
print("#####")
print(torch.tensor([[1,2], [3,5]])[0])
print("#####")
torch.tensor([[1,2], [3,5]])[0][0]

torch.Size([2, 2])
####
tensor([[[1, 2, 5],
         [3, 5, 5]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])
####
tensor([[1, 2],
        [3, 5]])
#####
tensor([1, 2])
#####


tensor(1)

In [38]:
print(torch.rand(2,2))
a = torch.rand(2,2)
b = torch.rand(2,2)
torch.matmul(a,b)  # dot product

tensor([[0.2933, 0.0872],
        [0.3823, 0.3824]])


tensor([[0.2230, 0.7561],
        [0.0485, 0.2586]])

In [50]:
# Specials
print(torch.zeros(2,3)) 
print("#")
print(torch.ones(2,2))
print("#")
print(torch.eye(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
#
tensor([[1., 1.],
        [1., 1.]])
#
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [61]:
import numpy as np
torch.from_numpy(np.zeros((2,2))) # torch.numpy()

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [79]:
# Class
class Student:
    def __init__(self, first, last, age):  # have to have 'self', but may contain other attributes
      self.first = first
      self.last = last
      self.age = age
    
    def Info(self):  # method
      print("The first name is " + self.first + " and the last name is " + self.last + ". It is " + str(self.age) + " years old")

    def birthday(self):
        self.age += 1

In [81]:
M1 = Student("John", "Doe", 30)
M1.Info()

The first name is John and the last name is Doe. It is 30 years old


In [82]:
# Creating a class of NN
import torch
import torch.nn as nn

class Net(nn.Module):  # inherit from nn.Module
  def __init__(self):
      super(Net, self).__init__()
      self.fc1 = nn.Linear(10, 20)  # Dense layer
      self.fc2 = nn.Linear(20, 20)  # Dense layer
      self.output = nn.Linear(20, 4)


  def forward(self, x):
      x = self.fc1(x)
      x = self.fc2(x)
      x = self.output(x)
      return x

In [91]:
MyNet = Net()
input = torch.rand(10)
MyNet.forward(input)   # return feedforward with the random weighted

tensor([ 0.1126,  0.0126,  0.0272, -0.3589], grad_fn=<AddBackward0>)